### ISSUE TITLE
Print function is broken in every image

### ISSUE THREAD

**Issue by vivek306** [Azure/AzureML-Containers#111]
![Print_Broken_ML](https://user-images.githubusercontent.com/2066108/182380041-a493849e-95db-4439-a066-0144d190abfd.png)

The issue seems to stem from https://pypi.org/project/azureml-inference-server-http/ not sure where to report it

**Comment by sshiri-msft** [comment]
@vivek306 Please provide the steps to reproduce it. 
And the version of azureml-inference-server-http
