### ISSUE TITLE
could you please add a cuda 10.1 container

### ISSUE THREAD

**Issue by snaik2016** [Azure/AzureML-Containers#12]
Please add cuda 10.1 container so that we can install pytorch 1.3

**Comment by lucas95123** [comment]
also facing same issue, pls add cuda 10.1 base image

**Comment by SubaMoorthy** [comment]
We tested torch 1.3 with mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.0-cudnn7-ubuntu16.04 and it works fine with this base image.  Also [Pytorch estimators ](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.dnn.pytorch?view=azure-ml-py) in azureml support 1.3 version now.

**Comment by jsleep** [comment]
@SubaMoorthy Could you please add CUDA 10.1 container with Ubuntu16.04? Ubuntu18.04 is incompatible with training transformer-style models with the hugging face library. This will enable us to use PyTorch1.5+.

openmpi3.1.2-cuda10.1-cudnn7-ubuntu16.04

**Comment by asears** [comment]
Is this fixed?  Here's a dockerfile using Ubuntu 18.04 with pytorch-gpu.

https://github.com/huggingface/transformers/blob/master/docker/transformers-pytorch-gpu/Dockerfile

**Comment by mx-iao** [comment]
We are working on adding a cuda 10.1 base image

**Comment by vizhur** [comment]
the image is available now
