### ISSUE TITLE
CUDA error 46 with CUDA 11.6 Ubuntu image and onnxruntime-gpu

### ISSUE THREAD

**Issue by friggog** [Azure/AzureML-Containers#126]
I am trying to run onnxruntime-gpu on an Azure Machine Learning instance with this base image: [openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04](https://github.com/Azure/AzureML-Containers/blob/master/base/gpu/openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04/Dockerfile) using CUDA. When trying to create an inference session I get this error:

```
  File "/azureml-envs/azureml_4ab38fdb3b18635e56f7e63921a429e8/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/azureml-envs/azureml_4ab38fdb3b18635e56f7e63921a429e8/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 46: all CUDA-capable devices are busy or unavailable ; GPU=0 ; hostname=c7b375a29d54407dad59b0dd621129a7000000 ; expr=cudaDeviceSynchronize(); 
```

I previously had this working with near identical environments using earlier versions of CUDA (e.g. [11.3](https://github.com/Azure/AzureML-Containers/blob/master/base/gpu/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04/Dockerfile) with onnxruntime-gpu 1.12) so I'm wondering if anything in the image has changed between these CUDA versions that could be causing issues for onnxruntime-gpu?

The only potential difference I can see is that the docker image uses cudnn 8.4 while the compatibility list for onnxruntime says cudnn 8.2, though I think 8.4 should be back compatible? The error given doesn't really seem to match this case either

Any advice would be much appreciated!

See also: https://github.com/microsoft/onnxruntime/issues/14030

**Comment by vizhur** [comment]
cuda compatibilities is probably a question for nvidia, though from the experience they have breaking changes in cuda's and cudnn's minor version updates. cudnn 8.4 is relatively old, probably latest onnx runtime should support that or have some plans for that.

We support limited matrix of the base images that work for majority of the scenarios, but you can use own image built on nvidia's cuda images with the set of drivers that work for your dependencies

**Comment by friggog** [comment]
I've found a solution not using CUDA/cuDNN from these base images but instead using the minimal base image and installing CUDA/cuDNN through conda. With CUDA/cuDNN versions that are the same as in the image (I think) everything seems to work ok which suggests something is funny with the image, but it is like nvidia's own image that would have the problem and not anything added here, so I think this can be closed
