### ISSUE TITLE
Wrong mpi version for openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04

### ISSUE THREAD

**Issue by clthorre** [Azure/AzureML-Containers#133]
https://github.com/Azure/AzureML-Containers/blob/da0e99b07e8b05d2645e1fd5894c23d471dabf4f/base/gpu/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04/Dockerfile#L79

The name of the dockerfile indicates that it should have openmpi 4.1.0 but it has 3.1.2

![image](https://user-images.githubusercontent.com/72841143/217493133-8d4327fa-5539-457d-ade8-53073dd52372.png)

**Comment by clthorre** [comment]
Hello can this issue please be addressed? Bugs in earlier versions of openmpi are causing my Azure Machine Learning jobs to fail and I am only able to use docker images based on the ones in this repo.

**Comment by vizhur** [comment]
@clthorre next update will have a fix for openmpi version. ETA is 06/10
