### ISSUE TITLE
Add statsmodels to the pre-installed packages

### ISSUE THREAD

**Issue by pawarbi** [Azure/AzureML-Containers#14]
Hi, 

Can you please add statsmodels to the azureml enviroment? It's the most widely used package in Python for time series analysis and other statistical analysis.

**Comment by vizhur** [comment]
python layer is defined through AzureML environment that gets materialized on top of the base image. Please specify necessary dependencies there or in a dockerfile itself
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.environment.environment?view=azure-ml-py
