### ISSUE TITLE
Installing conda.yml on top of curated environment (GPU+PyTorch)?

### ISSUE THREAD

**Issue by movingabout** [Azure/AzureML-Containers#148]
I'd like to use a curated environment with GPUs and PyTorch (e.g. `AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11-gpu`) and install python libraries based on a `conda.yml` on top.

How do I set this up correctly?

Ideally, I'd use the curated environment as a base image for a custom environment. But I'm having trouble setting the `image` parameter correctly.
Is that even possible? 
```
environment = Environment(
    image= # ---> how do I address the curated environment?
    name=ENVIRONMENT_NAME,
    conda_file=CONDA_YML_PATH,
)
ml_client.environments.create_or_update(environment)
```

Thanks!

**Comment by vizhur** [comment]
responded here: https://github.com/Azure/MachineLearningNotebooks/issues/1923
