### ISSUE TITLE
conda activate is not a valid command

### ISSUE THREAD

**Issue by JackCaster** [Azure/AzureML-Containers#156]
I want to create a custom dockerfile starting from `openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04` but conda does not seem to operate as expected. To simplify, the dockerfile would start with

```docker
FROM mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04
USER root
ENV DEBIAN_FRONTEND=noninteractive
```
and then I would like to add some more commands and create a custom conda env. However, even in this stripdown version, when I try to activate the base environment, I get
```
root@xxx# conda activate
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'activate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'doctor', 'env', 'content-trust')
```

The only way I can get `conda activate` to work is to type `conda init` first. But `conda init` does not work well with dockerfiles as it requires to reload the shell.

Have you set up conda to behave differently from default? Would you be able to help?

**Comment by JackCaster** [comment]
One solution would be to add 
```
ENV CONDA_ENV_NAME="your-env"
RUN \
    echo ". /opt/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate ${CONDA_ENV_NAME}"" >> ~/.bashrc
```
as done in https://hub.docker.com/r/continuumio/miniconda/dockerfile

**Comment by vizhur** [comment]
Conda is not friendly with docker. Solution above, unfortunately for some of scenarios only.
