### ISSUE TITLE
Containers not compatible with azure ml environment anymore

### ISSUE THREAD

**Issue by microsoft-sampsa** [Azure/AzureML-Containers#159]
Related to this: https://github.com/Azure/MachineLearningNotebooks/issues/950

Using this container as a basis for my environment: https://github.com/Azure/AzureML-Containers/tree/master/base/gpu/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04
breaks azure ml APIs with:
```
Linux distribution ubuntu 22.04 does not have automatic support. 
Missing packages: {'liblttng-ust.so.0'}
.NET Core 3.1 can still be used via `dotnetcore2` if the required dependencies are installed.
Visit https://aka.ms/dotnet-install-linux for Linux distro specific .NET Core install instructions.
Follow your distro specific instructions to install `dotnet-runtime-*` and replace `*` with `3.1.23`.
```
The sad thing is, that I am using azure provided container and azure APIs in azure ml cluster.  I would expect a bit more compatibility..

**Comment by vizhur** [comment]
This is a base container, it may not have dependencies you need. Feel free to install missing libraries and packages needed for your envirornment
