### ISSUE TITLE
openmpi4.1.0-ubuntu20.04:20240109.v1 upgraded python to 3.10

### ISSUE THREAD

**Issue by memoryz** [Azure/AzureML-Containers#170]
Version 20231130.v1 was still on python 3.8:
<img width="731" alt="image" src="https://github.com/Azure/AzureML-Containers/assets/6992432/362b81a5-39ea-472b-ba52-bb8d3a75f7f4">
But 20240109.v1 upgraded it to python 3.10:
<img width="739" alt="image" src="https://github.com/Azure/AzureML-Containers/assets/6992432/9acacebb-5611-4090-b921-4f527322e250">
It broke some dependencies in AML:
ERROR: Could not find a version that satisfies the requirement azureml-train-automl-runtime>=1.54.0.post1

From the [dockerfile](https://github.com/Azure/AzureML-Containers/blob/2a3deaee56571caa3ad757fa1d167b5dc476807c/base/cpu/openmpi4.1.0-ubuntu20.04/Dockerfile#L89), seems it should be using python 3.8?

**Comment by vizhur** [comment]
Base image update could have conda updates to keep up with the new bug fixes and features. We do not expect customers to use base environment, but follow best practices and use isolated conda environment. Hence that is not considered as a breaking change.
