### ISSUE TITLE
Python SDK V2

### ISSUE THREAD

**Issue by Uranium2** [Azure/AzureML-Containers#175]
In the `README.md` there's only the documentation on using the python SDK V1 

Example:

```python
from azureml.core import Environment

env = Environment.from_conda_specification(name='my-env', file_path='./conda_dependencies.yml')
```

But I can not manage to do the same using this package (AML SDK V2) https://pypi.org/project/azure-ai-ml/ 

```python
from azure.ai.ml.entities import BuildContext, Environment

azureml_env = Environment(
    build=BuildContext(
        path="./docker_context",
    ),
    name="my_experiment",
)
```

Where I have a `Dockerfile` + `conda_dependencies.yml` in the folder `docker_context` but it does not install the conda env with the selected package and python version.

Could you update or gives example with this SDK V2 in the README.md?

**Comment by vizhur** [comment]
v2 SDK supports docker context that gives you flexibility what spec or requirements files to pass to the resolver through dockerfile instructions. For samples you can check here https://github.com/Azure/azureml-examples, here https://github.com/Azure/azureml-assets/wiki/environments-documentation or here https://ml.azure.com/registries/azureml/environments 

v1 sample is for system managed environment, that is available in v2 as well. You need to pass both conda spec and desired base image.
