### ISSUE TITLE
new docker image build for cuda 12

### ISSUE THREAD

**Issue by jonathanreichhealthscope** [Azure/AzureML-Containers#192]
Hi there, we are facing some issues with using your pre-existing images to build a custom environment to host the deployment of an open-source LLM (Llama 2/3) that we are using for our ML pipelines that are hosted within the azure ecosystem.
The library we are relying upon, llama-cpp (or more specifically, the python wrapper called llama-cpp-python) contains pre-built binaries which we normally use to get GPU support for this library.
However, the documentation is explicit in than it requires a more recent version of cuda, namely 12.x (12.1 or 12.2 would be ideal for our use case).

This issue regarding CUDA versioning for pre-built binaries is mentioned here: https://pypi.org/project/llama-cpp-python/

And can be found in the section called 'pre-built wheel (new'):
![image](https://github.com/Azure/AzureML-Containers/assets/107975766/2e4a60a8-4740-49da-9fdc-c5952902ca3d)

TL-DR; we would like an image that is found within this directory: https://github.com/Azure/AzureML-Containers/tree/master/base/gpu
that has MPI support, the necessary libraries for azure ml functionality, and CUDA 12 support.

Thank you.

**Comment by martinResearch** [comment]
It would be amazing to have some rough estimate about when this could be added, so that we can make a more informed decision about the value of investing time in finding a workaround.

**Comment by vizhur** [comment]
next update for images will also include cuda12. ETA January

**Comment by keesschollaart81** [comment]
Fantastic. Howevert I run my CUDA 12 based container on Azure ML using the Python SDK (using `AmlCompute`, `Environment.image`, etc) and execute `nvidia-smi` I see the host still has driver 11.4:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
...
```
My container image is based on `pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime` and the error I get is:
```
UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0```

How can I get my AmlCluster to run CUDA 12?
