### ISSUE TITLE
Manifest for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:20240909.1 not found

### ISSUE THREAD

**Issue by eugencutic** [Azure/AzureML-Containers#200]
Hi

We are trying to use mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:20240909.1 as the base image for an AzureML environment: `FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20230103.v1`

We are getting a "not found" error:
```
2024-09-26T13:49:32: Step 1/10 : FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:20240909.1
2024-09-26T13:49:33: manifest for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:20240909.1 not found: manifest unknown: manifest tagged by "20240909.1" is not found
```

We get the same error message for `20240820.1` and `20240807.1`. 
We tried `20240909.v1`, hoping it would be a typo, but no luck.

Before this we were using `:20230103.v1` and it is working, but we need to upgrade because of vulnerabilities and we would prefer to pin a version, rather than use `:latest`.

The latest one that is working is `20240709.v1`, but we would like to use the latest release as of this moment. 

Any idea why `:20240909.1` is not found?

**Comment by vizhur** [comment]
it indeed does not exist. Here is the list of the tags

https://[mcr.microsoft.com/v2/azureml/openmpi4.1.0-ubuntu22.04/tags/list](https://mcr.microsoft.com/v2/azureml/openmpi4.1.0-ubuntu22.04/tags/list)

We'll update release notes
