### ISSUE TITLE
Image with Ubuntu 20.04?

### ISSUE THREAD

**Issue by corticalstack** [Azure/AzureML-Containers#27]
Likely an image with Ubuntu 20.04 is on it's way? Many thanks!

**Comment by jzazo** [comment]
Hi! Just wanted to re-ask this question after a few months of no response. We have interest in upgrading because of the new python version included in 20.04. Thanks!

**Comment by corticalstack** [comment]
And ping. Grateful for response from MS wrt AzureML image with Ubuntu 20.04

**Comment by MAQ-Ravijit-Ramana** [comment]
Hey, any updates on the image support for Ubuntu 20.04 ?

**Comment by MAQ-Ravijit-Ramana** [comment]
@vizhur

**Comment by vizhur** [comment]
we will add 20.04 images soon

**Comment by malthe** [comment]
@vizhur any progress on this to share?

**Comment by rshafique** [comment]
Hi any update one this one?

**Comment by v-a-s-a** [comment]
Yes. It would be great to have 20.04. It has been over 2 years since it was released.
