### ISSUE TITLE
Cuda 10.2 images not pushed in registry

### ISSUE THREAD

**Issue by mallamanis** [Azure/AzureML-Containers#32]
The images `openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04` and `openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04` do not seem pushed to the registry:

```
$ docker pull mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
Error response from daemon: manifest for mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04 not found: manifest unknown: manifest tagged by "openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04" is not found
```

**Comment by vizhur** [comment]
base-gpu image is deprecated. please consider to use 
mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
instead
