### ISSUE TITLE
Support plan for CUDA 11.0 and cuDNN 8.0 AML gpu container for tensorflow 2.4.x?

### ISSUE THREAD

**Issue by fujikosu** [Azure/AzureML-Containers#37]
I want to use tensorflow 2.4.x with AML as it started supporting mixed precision training in that version. But there is no matched CUDA version AML base container available yet. Are you planning to add it?

This is the tested environment for tensorflow 2.4.x stated in the official doc.

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0

link to the official doc is [here](https://www.tensorflow.org/install/source#linux)

Thank you!

**Comment by vizhur** [comment]
the image with requested capabilities is available now
https://github.com/Azure/AzureML-Containers/tree/master/base/gpu/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04
