### ISSUE TITLE
Vulnerabilities in Latest Images

### ISSUE THREAD

**Issue by gamullen** [Azure/AzureML-Containers#41]
My customer is using the *latest* AzureML image, but Azure Security Center (Qualys) is reporting issues with the image. They are concerned that a Microsoft-supplied image is flagged by Microsoft as being vulnerable.

How can we address this?

Thanks, Gary
![ASC - ML](https://user-images.githubusercontent.com/46575004/107584849-d073a780-6bc2-11eb-807c-8f3f526a064f.JPG)

**Comment by vizhur** [comment]
Vulnerabilities get addressed regularly, usually with a 2 weeks cadence

**Comment by lpasselin** [comment]
> Vulnerabilities get addressed regularly, usually with a 2 weeks cadence

@vizhur Is this still valid?
