### ISSUE TITLE
need containers compatible with PyTorch

### ISSUE THREAD

**Issue by fcampagnexandr** [Azure/AzureML-Containers#51]
PyTorch distributions support either CUDA 10.2 (pytorch 1.7.1)  or 11.1 (pytorch 1.8.1), but not 11.0. In order to help users of pytorch with prebuilt containers, this repo should offer a container built on top of nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04.

Trying to use PyTorch 1.8.1 and Microsoft DeepSpeed (which compiles CUDA extensions) with the latest provided container (https://github.com/Azure/AzureML-Containers/tree/master/base/gpu/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04) yield this error:

"Installed CUDA version 11.0 does not match the version torch was compiled with 11.1, unable to compile cuda/cpp extensions without a matching cuda version."

**Comment by JackCaster** [comment]
Agreed. I think I am facing a similar issue too. I can't make Pytorch 1.8.1 recognize the GPU in the virtual machine if I use the curated Docker image `mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04`

**Comment by JackCaster** [comment]
Kind reminder if anyone can take a look at this issue. Or is there a better place to post this?

**Comment by vizhur** [comment]
that's the right place for the post, we are working on adding that capability and it will be available with upcoming updates to the image

**Comment by junneyang** [comment]
> that's the right place for the post, we are working on adding that capability and it will be available with upcoming updates to the image

any update? we have the same problem...

**Comment by fcampagnexandr** [comment]
Anybody who is asking, given the lack of timely response, you may be better off modifying the 10.2 docker file and rebuilding the image yourself. We did this in April when I submitted the ticket and were up and running after that. Below is the adapted docker file we are using, but understand that it comes with absolutely no warranties.

`# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# Copied from https://github.com/Azure/AzureML-Containers/tree/master/base/gpu/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04,
# extended to install with CUDA 11.1 (initially cuda:11.0.3-devel-ubuntu18.04)
FROM mcr.microsoft.com/azureml/o16n-base/python-assets:20210210.31228572 AS inferencing-assets

# Tag: cuda:11.1.1-devel-ubuntu18.04
# Env: CUDA_VERSION=11.1.1
# Env: NCCL_VERSION=?
# Env: CUDNN_VERSION=8.?

FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04

USER root:root

ENV com.nvidia.cuda.version $CUDA_VERSION
ENV com.nvidia.volumes.needed nvidia_driver
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
ENV NCCL_DEBUG=INFO
ENV HOROVOD_GPU_ALLREDUCE=NCCL

# Install Common Dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    # SSH and RDMA
    libmlx4-1 \
    libmlx5-1 \
    librdmacm1 \
    libibverbs1 \
    libmthca1 \
    libdapl2 \
    dapl2-utils \
    openssh-client \
    openssh-server \
    redis \
    iproute2 && \
    # Others
    apt-get install -y \
    build-essential \
    bzip2 \
    libbz2-1.0 \
    systemd \
    git \
    wget \
    cpio \
    pciutils \
    libnuma-dev \
    ibutils \
    ibverbs-utils \
    rdmacm-utils \
    infiniband-diags \
    perftest \
    librdmacm-dev \
    libibverbs-dev \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libssl1.0.0 \
    linux-image-aws \
    linux-image-azure \
    linux-image-generic \
    linux-image-kvm \
    linux-image-lowlatency \
    linux-image-virtual \
    linux-image-gke \
    linux-image-oem \
    slapd \
    perl \
    ca-certificates \
    apt \
    p11-kit \
    libp11-kit0 \
    tar \
    fuse && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# Inference
# Copy logging utilities, nginx and rsyslog configuration files, IOT server binary, etc.
COPY --from=inferencing-assets /artifacts /var/
RUN /var/requirements/install_system_requirements.sh && \
    cp /var/configuration/rsyslog.conf /etc/rsyslog.conf && \
    cp /var/configuration/nginx.conf /etc/nginx/sites-available/app && \
    ln -s /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app && \
    rm -f /etc/nginx/sites-enabled/default
ENV SVDIR=/var/runit
ENV WORKER_TIMEOUT=300
EXPOSE 5001 8883 8888

# Conda Environment
ENV MINICONDA_VERSION py37_4.9.2
ENV PATH /opt/miniconda/bin:$PATH
RUN wget -qO /tmp/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
    bash /tmp/miniconda.sh -bf -p /opt/miniconda && \
    conda clean -ay && \
    rm -rf /opt/miniconda/pkgs && \
    rm /tmp/miniconda.sh && \
    find / -type d -name __pycache__ | xargs rm -rf

# Open-MPI-UCX installation
RUN mkdir /tmp/ucx && \
    cd /tmp/ucx && \
	wget -q https://github.com/openucx/ucx/releases/download/v1.6.1-rc2/ucx-1.6.1.tar.gz && \
	tar zxf ucx-1.6.1.tar.gz && \
	cd ucx-1.6.1 && \
	./configure --prefix=/usr/local --enable-optimizations --disable-assertions --disable-params-check --enable-mt && \
	make -j $(nproc --all) && \
	make install && \
	rm -rf /tmp/ucx

# Open-MPI installation
ENV OPENMPI_VERSION 4.1.0
RUN mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-${OPENMPI_VERSION}.tar.gz && \
    tar zxf openmpi-${OPENMPI_VERSION}.tar.gz && \
    cd openmpi-${OPENMPI_VERSION} && \
    ./configure --with-ucx=/usr/local/ --enable-mca-no-build=btl-uct --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi

# Msodbcsql17 installation
RUN apt-get update && \
    apt-get install -y curl && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17

#Cmake Installation
RUN apt-get update && \
    apt-get install -y cmake

RUN conda install python=3.7 pip=20.1.1 pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge &&  conda clean -aqy && \
    rm -rf /opt/miniconda/pkgs && find /opt/miniconda/ -type d -name __pycache__ -prune -exec rm -rf {} \;
RUN pip install --user pytorch-fast-transformers
RUN pip install mpi4py
RUN pip install deepspeed==0.3.14 cupy-cuda111 # see https://docs.cupy.dev/en/stable/install.html for cupy versions.
RUN pip install pydevd-pycharm==203.5981.165
RUN wget https://aka.ms/downloadazcopy-v10-linux ;  tar -xvf ./downloadazcopy-v10-linux ; mv azcopy_linux_amd64*/azcopy /usr/local/bin/
`

**Comment by JackCaster** [comment]
I agree that we could build our own custom Docker container, but I'd expect Azure to provide one that is up to date. I do not need to do custom things and, as per [doc](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-docker-image) 
> Microsoft may not be able to help troubleshoot problems caused by a custom image. If you encounter problems, you may be asked to use the default image or one of the images Microsoft provides to see if the problem is specific to your image.

so I'd like to avoid creating problems that will be hard to debug---particularly in corporate contexts.

Looking forward to receiving updates.

**Comment by vizhur** [comment]
@JackCaster Microsoft might not be able to help, but will definitely try to do its best to help users. As well as open source community is very responsive on those kind of questions. Many customers are using custom containers to address special requirements for their scenarios. I would agree with @fcampagnexandr to give it a try with custom container and cuda 11.1 from Microsoft will be available with upcoming weeks

**Comment by jsleep** [comment]
Following up on this, as I depend on CUDA11.1 for training on A100's now.

**Comment by v-vvogir** [comment]
The image is released to MCR with Cuda 11.1. More information on image and release notes can be found here - https://github.com/Azure/AzureML-Containers
