### ISSUE TITLE
Unable to build image with GPU for an Azure ML environment inference

### ISSUE THREAD

**Issue by PradeepThapa** [Azure/AzureML-Containers#64]
Getting an error message with 
**WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
>>>   docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /mnt/docker/overlay2/djf6dfd8f7d8f7dfa88d8/merged/run/nvidia-persistenced/socket: no such device or address: unknown.**

when I try to build a GPU image "openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04", I encountered this error. I tried building from Dockerfile which still throws an error.

**Comment by vizhur** [comment]
Please check your local docker settings. This image is built on a regular schedule with local and ACR builds with no issues.
