### ISSUE TITLE
vulnerability for USN-5254-1

### ISSUE THREAD

**Issue by sergey-ivanchuk** [Azure/AzureML-Containers#84]
Hello,

It seems that all the `Dockerfile`s in this repo are now getting flagged for [USN-5254-1](https://ubuntu.com/security/notices/USN-5254-1) via Qualys security scans. The CVSS score is 9.8 / 10.

For example, this code would be considered a vulnerability --
```python3
from azureml.core.environment import Environment
myenv = Environment(name="deployment-azureml")
myenv.docker.base_image = "mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20220127.v1"
...
...
```

In the Dockerfiles, would you consider adding the following? This seems to be appropriate resolution. 
```Dockerfile
RUN apt-get update && apt-get install --only-upgrade passwd=1:4.5-1ubuntu2.2 -y \
        && apt-get install --only-upgrade login=1:4.5-1ubuntu2.2 -y && \
        apt-get install --only-upgrade uidmap=1:4.5-1ubuntu2.2 -y
```

**Comment by sergey-ivanchuk** [comment]
@vizhur for visibility. I'm not sure who to assign or tag here.

**Comment by sergey-ivanchuk** [comment]
Could anyone from Microsoft provide some feedback here?

**Comment by vizhur** [comment]
Hi @sergey-ivanchuk 

we are working on the fix for USN-5254-1 for GPU images and planned to ship by the end of the week

**Comment by sergey-ivanchuk** [comment]
> Hi @sergey-ivanchuk
> 
> we are working on the fix for USN-5254-1 for GPU images and planned to ship by the end of the week

Will [cpu](https://github.com/Azure/AzureML-Containers/tree/master/base/cpu) containers also be patched either next week or in the future ? Majority of AzureML real time endpoints are running on CPU-based containers like [openmpi3.1.2-ubuntu18.04](https://github.com/Azure/AzureML-Containers/tree/master/base/cpu/openmpi3.1.2-ubuntu18.04) and [openmpi4.1.0-ubuntu20.04](https://github.com/Azure/AzureML-Containers/tree/master/base/cpu/openmpi4.1.0-ubuntu20.04)

**Comment by vizhur** [comment]
those will be updated too

**Comment by vizhur** [comment]
latest CPU images were updated on Feb 08 and should address the vulnerability. can you please try this
mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20220208.v1

**Comment by sergey-ivanchuk** [comment]
yep, I was able to confirm after a few tests. 

`mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20220208.v1` seems to pass all Qualys checks.

`mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04:20220208.v1` still gets flagged for USN-5254-1

**Comment by sergey-ivanchuk** [comment]
Hi @vizhur and team, I believe the issue is still persisting for GPU-based docker images.

Here's one example

My Dockerfile --
```
FROM mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04:20220303.v1
```

Library checks --
```bash
$ dpkg -l '*login*'
ii  login                        1:4.5-1ubuntu2      amd64               system login tools

$ dpkg -l '*passwd*'
ii  base-passwd                  3.5.44              amd64               Debian base system master password and group files
ii  passwd                       1:4.5-1ubuntu2      amd64               change and administer password and group data
```

I believe in both cases version `1:4.5-1ubuntu2.2` is needed (2.2 vs 2)
