### ISSUE TITLE
openmpi4.1.0-ubuntu20.04 :  msodbcsql The EULA was not accepted. Installation aborted.

### ISSUE THREAD

**Issue by janvanuytrecht** [Azure/AzureML-Containers#86]
When building our dockerfile we get this:

Preparing to unpack .../8-msodbcsql17_17.9.1.1-1_amd64.deb ...
ERROR: The EULA was not accepted. Installation aborted.
dpkg: error processing archive /tmp/apt-dpkg-install-9b04va/8-msodbcsql17_17.9.1.1-1_amd64.deb (--unpack):
 new msodbcsql17 package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /tmp/apt-dpkg-install-9b04va/8-msodbcsql17_17.9.1.1-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I've got this issue for all tags, also with the ubuntu 18.04 version.
Since two weeks our builds fail because of this issue.

run command in our dockerfile:

RUN apt-get update -y && apt-get upgrade -y &&
apt-get install build-essential -y --no-install-recommends &&
apt-get clean

**Comment by janvanuytrecht** [comment]
run command in our dockerfile:

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install build-essential -y --no-install-recommends && \
    apt-get clean

**Comment by vizhur** [comment]
would you mind to share your dockerfile?
