### ISSUE TITLE
Add CMAKE to base image

### ISSUE THREAD

**Issue by yueguoguo** [Azure/AzureML-Containers#9]
Many enterprise users are using the Microsoft Recommenders repository (https://github.com/Microsoft/Recommenders) to build their customized recommender solution on Azure. To build a content-based recommender by using sparse feature data, field-aware factorization machine (FFM) is usually used. One of the most popular implementations of such algorithm is xlearn (https://github.com/aksnzhy/xlearn) which is developed in C++ and relies on CMAKE to build. However, since CMAKE is not available in the base Docker image of AzureML service (it is missing in the Docker file for the base image, which can be found in https://github.com/Azure/AzureML-Containers/blob/master/base/cpu/intelmpi2018.3-ubuntu16.04/Dockerfile), installation of xlearn failed when AzureML service initializes an experiment. 

This, in turn, breaks the pipeline that customer want to use for building a FFM model for their recommender system. It also fails the CI/CD pipeline of the Microsoft/Recommender repository where AzureML service is used for unit/integration/smoke testing.

It is worth noting that, CMAKE is used not just for the xlearn package, but also many other popular packages like OpenCV, Caffe, etc.. Therefore, supporting CMAKE in the base image will support a variety of different AI workloads on AzureML service. 

Just to know if there is a plan for supporting CMAKE in the base image. It should be fairly easy and does not add much weight to the image. Thanks!

**Comment by adriennn** [comment]
It is also required for latest xgboost versions.

**Comment by mohit-sh** [comment]
Any updates on this?

**Comment by mohit-sh** [comment]
I've put together a dockerfile with cmake support that works for me. Putting here if anyone else finds it useful --  https://gist.github.com/mohit-sh/cb2a22f2f08292d441e01348790bc9d7

**Comment by vizhur** [comment]
cmake could be installed through conda or pip. there is also a possibility to extend the base image and add cmake if needed. some of the new images will have cmake
