### ISSUE TITLE
CUDNN 8.1

### ISSUE THREAD

**Issue by Soppe** [Azure/AzureML-Containers#91]
Hi,
I've been trying to use the openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04 image together with Tenserflow 2.7 and 2.8, but i'm having no luck as these require cuDNN 8.1, whereas the image comes with 8.0.5. I get errors that boils down to the following:
E tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded runtime cuDNN library: 8.0.5 but source was compiled with: 8.1.0

I haven't been able to try the curated environments found in the azure ml workspace portal as my code have dependencies not supported by the curated environment i can't remove without breaking it, but i fail to see how the ones using tf 2.5+ can work when there aren't any evident changes being made to the CUDA/cuDNN versions in their related docker images.

Is there a fairly simple way to update the cuDNN version to 8.1, or am i stuck having to create my own docker image?

**Comment by davystrong** [comment]
I'm facing the same issue. Any update on this?

**Comment by vizhur** [comment]
we will be adding a new base image with a newer cuda driver.
