### ISSUE TITLE
mismatch of tags for docker container images

### ISSUE THREAD

**Issue by sergey-ivanchuk** [Azure/AzureML-Containers#93]
Hi everyone,

I noticed the following:

for container `openmpi3.1.2-ubuntu18.04` tag of `20220401.v1` from https://github.com/Azure/AzureML-Containers/blob/3f597d09481703189af7283c39d03071f20622a8/base/cpu/openmpi3.1.2-ubuntu18.04/release-notes.md

for container `openmpi3.1.2-ubuntu18.04` tag of `20220329.v1` from https://mcr.microsoft.com/v2/azureml/openmpi3.1.2-ubuntu18.04/tags/list

Could Microsoft clear up documentation or the listed tags for releases? I'm not sure which would be 'right', but I imagine either could be possible to update. Thank you for doing so.

**Comment by vizhur** [comment]
Thank you Sergey for reporting the issue. We'll update the tags
