### ISSUE TITLE
Current version of OpenMPI image is broken

### ISSUE THREAD

**Issue by sdebruyn** [Azure/AzureML-Containers#98]
CPU version of openmpi3.1.2-ubuntu18.04 is broken

At startup an error is thrown saying that the package opencensus was not found.

Broken at this point: `mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04@sha256:10bce3eb1baa47a7f8b0b997804454496361e55535b83185d5826f44d8794f82`

Last version known to work: `mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04@sha256:7b2748bbf455a2d5adc8dd5af3c5c7890a23ef8336458251b6ebd5093f91eca0`

I see you always commit spaces just to trigger new builds and let the apt-get install run again to get the latest version of each package in ubuntu. Please set fixed versions in the apt-get installations so that the builds are reproducible and we can track changes to individual packages.

**Comment by sdebruyn** [comment]
Simply changing our tags between the 2 images listed above causes/fixes the issue for us. It seems that an underlying library installed in the `apt-get` step causes this dependency

**Comment by vizhur** [comment]
did you build with the previous version or you simply hit the cache?
